version: '3.8'

services:
  api:
    build:
      context: ./ 
      dockerfile: Dockerfile
    container_name: attendance_api
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=db;Database=AttendanceDb;User Id=sa;Password=${SA_PASSWORD};TrustServerCertificate=True;
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: attendance_db
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: ${SA_PASSWORD}
    ports:
      - '1433:1433'
    volumes:
      - sqlserver_data:/var/opt/mssql
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-Usa", "-P${SA_PASSWORD}", "-Q", "select 1"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  sqlserver_data: